### ISSUE TITLE
Stuck at Fetching 16 files:   0%|          | 0/16 [00:00<?, ?it/s]

### ISSUE THREAD

**Issue by prophet1996** [agiresearch/OpenAGI#18]
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/16836510/236882812-71822b1c-6c5c-4da3-b721-ece0fbc08e59.png">

**Comment by TobyGE** [comment]
I think the problem comes from "transformers". Can you open a new notebook and try to load other models from transformers, and let me know the results?
