### ISSUE TITLE
No codes for few-shot, fine-tuning, RLTF and other models?

### ISSUE THREAD

**Issue by HenryHZY** [agiresearch/OpenAGI#2]
Hi @TobyGE @davidbyttow @evison @agiresearch 

I just find the Jupyter Notebook for GTP3.5 + zero-shot. Do you have a plan to release the codes for few-shot, fine-tuning, RLTF and other models? 

By the way, the Arxiv paper lacks experimental results (i.e., only Table 5 provides weighted average results).

**Comment by agiresearch** [comment]
Dear @HenryHZY, the zero-shot and fine-tuning is already here; few-shot and RLTF are under organization and adding comments for better code readability, will be here very soon.

**Comment by HenryHZY** [comment]
@agiresearch Thanks for your quick reply. Also looking forward to more detailed experimental results:)
