### ISSUE TITLE
Exposed API Key

### ISSUE THREAD

**Issue by nahatx** [agiresearch/OpenAGI#23]
https://github.com/agiresearch/OpenAGI/blob/c1ce7595c8e1cfea1bbb9d83beca7b0bb5893360/open_tasks/tools/customized_tools.py#L26

Howdy,

Do not expose your API key in your source code.

Instead, consider storing it an environment variable, or using a key management service, or even software such as Vault.
Then be sure to rotate your API key after it is safely stored, or else it may still be recoverable in your commit history.

Also, see Openai's best practices page for api keys for more details:
https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety

**Comment by TobyGE** [comment]
Thank you for your helpful suggestions. I have disabled the API key prior to the release. Nonetheless, I appreciate your support and concern.
